//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeColor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Results = new HashSet<Results>();
        }
    
        public int id { get; set; }
        public Nullable<int> Age { get; set; }
        public string Activity { get; set; }
        public string Gender { get; set; }
        public string NewId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Results> Results { get; set; }

        public Users(int age, string activity, string gender, string newId) : base()
        {
            Age = age;
            Activity = activity;
            Gender = gender;
            NewId = newId;
        }

        public bool CompareTo(Users user)
        {
            return (string.Compare(user.Activity.ToLower(), Activity.ToLower()) == 0 && user.Age == Age && string.Compare(user.Gender.ToLower(), Gender.ToLower()) == 0);
        }

    }
}
