//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeColor.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Points
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Points()
        {
            this.Results = new HashSet<Results>();
        }

        [Key]
        public int id { get; set; }

        public Nullable<int> testid { get; set; }
        public string color { get; set; }
        public string Symbol { get; set; }

        [ForeignKey(nameof(testid))]
        public virtual Tests Tests { get; set; }

        public virtual ICollection<Results> Results { get; set; }
    }
}
